/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joshu
 */
public class OrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetail
     */
    public OrderDetail() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        DetailPesanan = new javax.swing.JLabel();
        PanelPemesanan = new javax.swing.JPanel();
        Gambar1 = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        Lokasi = new javax.swing.JLabel();
        JenisTiket = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();
        JenisTiketDiambil = new javax.swing.JLabel();
        HargaTiketDiambil = new javax.swing.JLabel();
        JumlahDiambil = new javax.swing.JLabel();
        InformasiPelanggan = new javax.swing.JLabel();
        PanelInformasiPelanggan = new javax.swing.JPanel();
        NamaLengkap = new javax.swing.JLabel();
        NamaLengkapTextField = new javax.swing.JTextField();
        NomorPonsel = new javax.swing.JLabel();
        NomorPonselTextField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PanelHarga = new javax.swing.JPanel();
        DetailHarga = new javax.swing.JLabel();
        TotalHargaTiket = new javax.swing.JLabel();
        HargaTiket = new javax.swing.JLabel();
        BiayaLayanan = new javax.swing.JLabel();
        HargaBiayaLayanan = new javax.swing.JLabel();
        TotalLayanan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BayarTiketButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 87, 166));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        DetailPesanan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        DetailPesanan.setText("Detail Pesanan");

        PanelPemesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Intimate Concert 'RINDU SELALU' bersama J-ROCKS (1).jpg"))); // NOI18N

        Judul.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Judul.setText("Intimate Concert 'Rindu Selalu' bersama...");
        Judul.setToolTipText("");

        Tanggal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Tanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        Tanggal.setText("28 June 2025");

        Waktu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Waktu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time.png"))); // NOI18N
        Waktu.setText("18:00 - 22:00 WIB");

        Lokasi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Lokasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location.png"))); // NOI18N
        Lokasi.setText("Swiss-Belhotel Pondok Indah, DKI Jakarta");

        JenisTiket.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        JenisTiket.setText("Jenis Tiket");

        Harga.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Harga.setText("Harga");

        Jumlah.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Jumlah.setText("Jumlah");

        JenisTiketDiambil.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        JenisTiketDiambil.setText("Dinner Package");

        HargaTiketDiambil.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        HargaTiketDiambil.setText("Rp361.250");

        JumlahDiambil.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        JumlahDiambil.setText("x1");

        javax.swing.GroupLayout PanelPemesananLayout = new javax.swing.GroupLayout(PanelPemesanan);
        PanelPemesanan.setLayout(PanelPemesananLayout);
        PanelPemesananLayout.setHorizontalGroup(
            PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelPemesananLayout.createSequentialGroup()
                        .addComponent(Gambar1)
                        .addGap(18, 18, 18)
                        .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Judul)
                            .addComponent(Tanggal)
                            .addComponent(Waktu)
                            .addComponent(Lokasi)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPemesananLayout.createSequentialGroup()
                        .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JenisTiket)
                            .addComponent(JenisTiketDiambil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Harga)
                            .addComponent(HargaTiketDiambil))
                        .addGap(55, 55, 55)
                        .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jumlah)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPemesananLayout.createSequentialGroup()
                                .addComponent(JumlahDiambil)
                                .addGap(31, 31, 31)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPemesananLayout.setVerticalGroup(
            PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPemesananLayout.createSequentialGroup()
                        .addComponent(Judul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Waktu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lokasi))
                    .addComponent(Gambar1))
                .addGap(28, 28, 28)
                .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JenisTiket)
                    .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Harga)
                        .addComponent(Jumlah)))
                .addGap(18, 18, 18)
                .addGroup(PanelPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JenisTiketDiambil)
                    .addComponent(HargaTiketDiambil)
                    .addComponent(JumlahDiambil))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        InformasiPelanggan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        InformasiPelanggan.setText("Informasi Pelanggan");

        PanelInformasiPelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NamaLengkap.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        NamaLengkap.setText("Nama Lengkap:");

        NomorPonsel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        NomorPonsel.setText("Nomor Ponsel:");

        Email.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Email.setText("Email:");

        javax.swing.GroupLayout PanelInformasiPelangganLayout = new javax.swing.GroupLayout(PanelInformasiPelanggan);
        PanelInformasiPelanggan.setLayout(PanelInformasiPelangganLayout);
        PanelInformasiPelangganLayout.setHorizontalGroup(
            PanelInformasiPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformasiPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInformasiPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomorPonselTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(NamaLengkapTextField)
                    .addComponent(NamaLengkap)
                    .addComponent(NomorPonsel))
                .addGap(88, 88, 88)
                .addGroup(PanelInformasiPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInformasiPelangganLayout.setVerticalGroup(
            PanelInformasiPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformasiPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInformasiPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaLengkap)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInformasiPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(NamaLengkapTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomorPonsel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomorPonselTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        PanelHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DetailHarga.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        DetailHarga.setText("Detail Harga");

        TotalHargaTiket.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        TotalHargaTiket.setText("Total Harga Tiket");

        HargaTiket.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        HargaTiket.setText("Rp361.250");

        BiayaLayanan.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        BiayaLayanan.setText("Biaya Layanan");

        HargaBiayaLayanan.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        HargaBiayaLayanan.setText("Rp0");

        TotalLayanan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        TotalLayanan.setText("Total Layanan");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Rp361.250");

        BayarTiketButton.setBackground(new java.awt.Color(0, 87, 166));
        BayarTiketButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        BayarTiketButton.setForeground(new java.awt.Color(255, 255, 255));
        BayarTiketButton.setText("Bayar Tiket");

        javax.swing.GroupLayout PanelHargaLayout = new javax.swing.GroupLayout(PanelHarga);
        PanelHarga.setLayout(PanelHargaLayout);
        PanelHargaLayout.setHorizontalGroup(
            PanelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHargaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHargaLayout.createSequentialGroup()
                        .addComponent(DetailHarga)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelHargaLayout.createSequentialGroup()
                        .addComponent(TotalHargaTiket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(HargaTiket)
                        .addGap(33, 33, 33))
                    .addGroup(PanelHargaLayout.createSequentialGroup()
                        .addComponent(BiayaLayanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HargaBiayaLayanan)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHargaLayout.createSequentialGroup()
                        .addComponent(TotalLayanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHargaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BayarTiketButton)
                .addGap(18, 18, 18))
        );
        PanelHargaLayout.setVerticalGroup(
            PanelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHargaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DetailHarga)
                .addGap(18, 18, 18)
                .addGroup(PanelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalHargaTiket)
                    .addComponent(HargaTiket))
                .addGap(18, 18, 18)
                .addGroup(PanelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiayaLayanan)
                    .addComponent(HargaBiayaLayanan))
                .addGap(30, 30, 30)
                .addGroup(PanelHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLayanan)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BayarTiketButton)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DetailPesanan)
                    .addComponent(PanelPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformasiPelanggan)
                    .addComponent(PanelInformasiPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(PanelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DetailPesanan)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InformasiPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelInformasiPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(PanelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarTiketButton;
    private javax.swing.JLabel BiayaLayanan;
    private javax.swing.JLabel DetailHarga;
    private javax.swing.JLabel DetailPesanan;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel Gambar1;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel HargaBiayaLayanan;
    private javax.swing.JLabel HargaTiket;
    private javax.swing.JLabel HargaTiketDiambil;
    private javax.swing.JLabel InformasiPelanggan;
    private javax.swing.JLabel JenisTiket;
    private javax.swing.JLabel JenisTiketDiambil;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel JumlahDiambil;
    private javax.swing.JLabel Lokasi;
    private javax.swing.JLabel NamaLengkap;
    private javax.swing.JTextField NamaLengkapTextField;
    private javax.swing.JLabel NomorPonsel;
    private javax.swing.JTextField NomorPonselTextField;
    private javax.swing.JPanel PanelHarga;
    private javax.swing.JPanel PanelInformasiPelanggan;
    private javax.swing.JPanel PanelPemesanan;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel TotalHargaTiket;
    private javax.swing.JLabel TotalLayanan;
    private javax.swing.JLabel Waktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
