import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joshu
 */
public class Ticket extends javax.swing.JFrame {
    private static Connection conn;
    private static Statement stmt;
    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
        connectToDatabase();
    }
    
    private void connectToDatabase(){
        try {
            String DB = "jdbc:sqlserver://localhost:1433;databaseName=Loketku;encrypt=true;trustServerCertificate=true";
            String user = "sa";
            String pass = "Purba_123";
            conn = DriverManager.getConnection(DB, user, pass);
            stmt = conn.createStatement();
            System.out.println("Berhasil terkoneksi dengan database Loketku");
        } catch (SQLException e) {
            System.out.println("Gagal terkoneksi dengan database: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAtas = new javax.swing.JPanel();
        PanelTiket = new javax.swing.JPanel();
        NomorPesanan = new javax.swing.JLabel();
        KodePemesanan = new javax.swing.JLabel();
        Tanggalpemesanan = new javax.swing.JLabel();
        Gambar = new javax.swing.JLabel();
        JudulKonser = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        Lokasi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InfoTiket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAtas.setBackground(new java.awt.Color(0, 87, 166));
        PanelAtas.setPreferredSize(new java.awt.Dimension(1200, 200));

        javax.swing.GroupLayout PanelAtasLayout = new javax.swing.GroupLayout(PanelAtas);
        PanelAtas.setLayout(PanelAtasLayout);
        PanelAtasLayout.setHorizontalGroup(
            PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelAtasLayout.setVerticalGroup(
            PanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PanelTiket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NomorPesanan.setBackground(new java.awt.Color(255, 255, 255));
        NomorPesanan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NomorPesanan.setForeground(new java.awt.Color(153, 153, 153));
        NomorPesanan.setText("Kode Pesanan:");

        KodePemesanan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KodePemesanan.setText("WER4EBCX");

        Tanggalpemesanan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Tanggalpemesanan.setForeground(new java.awt.Color(153, 153, 153));
        Tanggalpemesanan.setText("Monday, 02 June 2025");

        Gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Intimate Concert 'RINDU SELALU' bersama J-ROCKS (1).jpg"))); // NOI18N

        JudulKonser.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        JudulKonser.setText("Intimate Concert 'RINDU SELALU' bersama...");

        Tanggal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Tanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        Tanggal.setText("28 June 2025");

        Waktu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Waktu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time.png"))); // NOI18N
        Waktu.setText("18:00 - 22:00 WIB");

        Lokasi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Lokasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location.png"))); // NOI18N
        Lokasi.setText("Swiss-Belhotel Pondok Indah, DKI Jakarta");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Info Tiket");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-06-02 211055.png"))); // NOI18N
        jLabel2.setText("1 Ticket Dinner Package");

        javax.swing.GroupLayout PanelTiketLayout = new javax.swing.GroupLayout(PanelTiket);
        PanelTiket.setLayout(PanelTiketLayout);
        PanelTiketLayout.setHorizontalGroup(
            PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTiketLayout.createSequentialGroup()
                        .addComponent(Gambar)
                        .addGap(18, 18, 18)
                        .addGroup(PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JudulKonser)
                            .addComponent(Tanggal)
                            .addComponent(Waktu)
                            .addComponent(Lokasi))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(PanelTiketLayout.createSequentialGroup()
                        .addComponent(NomorPesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KodePemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tanggalpemesanan)
                        .addGap(22, 22, 22))
                    .addGroup(PanelTiketLayout.createSequentialGroup()
                        .addGroup(PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelTiketLayout.setVerticalGroup(
            PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomorPesanan)
                    .addComponent(KodePemesanan)
                    .addComponent(Tanggalpemesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gambar)
                    .addGroup(PanelTiketLayout.createSequentialGroup()
                        .addComponent(JudulKonser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Waktu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lokasi)))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        InfoTiket.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        InfoTiket.setText("Informasi Tiket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAtas, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoTiket)
                    .addComponent(PanelTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(594, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private javax.swing.JLabel InfoTiket;
    private javax.swing.JLabel JudulKonser;
    private javax.swing.JLabel KodePemesanan;
    private javax.swing.JLabel Lokasi;
    private javax.swing.JLabel NomorPesanan;
    private javax.swing.JPanel PanelAtas;
    private javax.swing.JPanel PanelTiket;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Tanggalpemesanan;
    private javax.swing.JLabel Waktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
